### ISSUE TITLE
There is no "monoBitTest" test

### ISSUE THREAD

**Issue by DanielSWolf** [runk/randomness#426]
According to [the docs](https://www.npmjs.com/package/randomness#:~:text=ones%20is%20necessary.-,monoBitTest,-%3A%20Monobit%20test.%20The), there is a test called `monoBitTest`. Really, its name is `monobitTest` with a lower-case "b". 

Usually, TypeScript would spot this problem immediately. However, the TypeScript exports don't seem to include the individual tests, but only an object `tests: Record<string, RandomnessTest>`, so that TypeScript cannot check the test names. It might be a good idea to make the typings more type-safe, e.g. by adding explicit named exports for the individual tests.

**Comment by runk** [comment]
Thanks for report, this is fixed now.
